#' Exit VCQI program at the end of a run or after an error
#'
#' @param VCP VCQI current program name to be logged, default to be the function name
#' @param halt_message Error text to print when VCQI is stopped mid-run
#'
#' @return Clean exit from VCQI programs
#'
#' @importFrom stringr str_detect
#' @import openxlsx
#' @importFrom rlang abort

# vcqi_halt_immediately R version 1.07 - Biostat Global Consulting - 2023-10-03
# ******************************************************************************
# Change log

# Date 			  Version 	Name			      What Changed
# 2022-07-08  1.00      Caitlin Clary   Original R version
# 2022-09-17  1.01      Mia Yu          Fill out some TO DO
# 2022-09-22  1.02      Caitlin Clary   Add billboard
# 2022-10-18  1.03      Caitlin Clary   Package version, testing stop procedure
# 2022-10-27  1.04      Caitlin Clary   if(file.exists) statements when removing
#                                       <program>_TEMP_DATASETS
# 2022-11-03  1.05      Caitlin Clary   Backup process if logfile doesn't have
#                                       the correct headers
# 2022-12-06  1.06      Caitlin Clary   Backup process if Log sheet is missing in TO
# 2023-10-03  1.07      Mia Yu          Add call to miss_vcqi_halt_immediately
#                                       if used in MISS VCQI
# ******************************************************************************

# IN PROGRESS

vcqi_halt_immediately <- function(
    VCP = "vcqi_halt_immediately",
    halt_message = NA
){

  if(vcqi_object_exists("VCQI_HALT_PROGRAM_NAME")){
    miss_vcqi_halt_immediately()
  }

  vcqi_log_comment(VCP, 5, "Flow", "Starting")

  if(VCQI_CHECK_INSTEAD_OF_RUN != 1){

    # **************************************************************************
    # If the user made organ pipe plots and saved accompanying datasets, augment
    # those datasets with the cluster names

    if(vcqi_object_value("MAKE_PLOTS", 1) &
       vcqi_object_value("VCQI_MAKE_OP_PLOTS", 1) &
       vcqi_object_value("VCQI_SAVE_OP_PLOT_DATA", 1)){
      add_HH_vars_to_opplot_datasets()
    }

    # **************************************************************************
    # If the user executed some COVG_DIFF_01 hypothesis tests, export file to Excel

    # PLACEHOLDER FOR FUTURE MODULE

    # **************************************************************************
    # If the user executed some COVG_DIFF_02 hypothesis tests, export file to Excel

    # PLACEHOLDER FOR FUTURE MODULE

    # ****************************************************************************
    # If the user has specified to keep the temp databases, run program to append
    # all databases into one database

    if(vcqi_object_value("DELETE_VCQI_DATABASES_AT_END", 0) &
       vcqi_object_value("AGGREGATE_VCQI_DATABASES", 1) &
       !vcqi_object_value("VCQI_GENERATE_DATABASES", 0)){
      aggregate_vcqi_databases()
    }

    #  If user specified to delete databases put a comment in the log
    if(vcqi_object_value("DELETE_VCQI_DATABASES_AT_END", 1)){
      vcqi_log_comment(VCP, 3, "Comment",
                       "User has specified that VCQI databases should all be deleted.")
    }

    if(vcqi_object_value("DELETE_VCQI_DATABASES_AT_END", 1) |
       (vcqi_object_value("DELETE_VCQI_DATABASES_AT_END", 0) &
        vcqi_object_value("AGGREGATE_VCQI_DATABASES", 1))){

      # Note: this will erase all files that end in _database.dta in the output
      # folder...even if those files were generated by an earlier VCQI run. This
      # makes it important to direct the output of each run to its own output
      # folder

      if(vcqi_object_exists("VCQI_DATABASES")){
        for(f in seq_along(VCQI_DATABASES)){
          vcqi_log_comment(VCP, 3, "Comment",
                           paste0("Erasing ", VCQI_DATABASES[f], ".rds"))
          if(stringr::str_detect(VCQI_DATABASES[f], ".rds")){
            file.remove(paste0(VCQI_OUTPUT_FOLDER, "/", VCQI_DATABASES[f]))
          } else {
            file.remove(paste0(VCQI_OUTPUT_FOLDER, "/", VCQI_DATABASES[f], ".rds"))
          }
        }
      }
    }

    # **************************************************************************
    # Delete VCQI temp datasets if the user requests it. Most of the measures
    # clean up after themselves, but there are some temporary datasets that
    # persist across measures; clean those up here.

    if(vcqi_object_value("DELETE_TEMP_VCQI_DATASETS", 1)){
      #datasetlist <- c(TT_TEMP_DATASETS, RI_TEMP_DATASETS, SIA_TEMP_DATASETS, MISC_TEMP_DATASETS)
      if (!vcqi_object_exists("RI_TEMP_DATASETS")){
        RI_TEMP_DATASETS <- NULL
      }
      #For now we only have RI programs
      datasetlist <- RI_TEMP_DATASETS

      for (d in seq_along(datasetlist)) {
        vcqi_log_comment(VCP,3,"Cleanup",
                         paste0("Erasing temp dataset ", datasetlist[d]))
        if (stringr::str_detect(datasetlist[d], ".rds")) {
          file.remove(paste0(VCQI_OUTPUT_FOLDER, "/", datasetlist[d]))
        } else {
          file.remove(paste0(VCQI_OUTPUT_FOLDER, "/", datasetlist[d], ".rds"))
        }
      } # end d loop

      programs <- c(
        "TT_COVG_01", "SIA_COVG_01", "SIA_COVG_02", "SIA_COVG_03",
        "SIA_COVG_04", "SIA_COVG_05", "SIA_QUAL_01", "RI_ACC_01",
        "RI_CONT_01", "DESC_01", "DESC_02", "DESC_03",
        "RI_COVG_01", "RI_COVG_02", "RI_COVG_03", "RI_COVG_04",
        "RI_COVG_05", "RI_QUAL_01", "RI_QUAL_02", "RI_QUAL_03",
        "RI_QUAL_04", "RI_QUAL_05", "RI_QUAL_06", "RI_QUAL_07",
        "RI_QUAL_07B", "RI_QUAL_08", "RI_QUAL_09", "RI_QUAL_12",
        "RI_QUAL_13", "RI_CCC_01", "RI_CCC_02", "RI_CIC_01",
        "RI_CIC_02", "COVG_DIFF_01", "COVG_DIFF_02", "RI_VCTC_01")

      # Note 2022-10-27: some RI_QUAL_09 datasets are logged in VCQI_DATABASES
      # and in RI_QUAL_09_TEMP_DATASETS - they are removed with VCQI_DATABASES
      # earlier in this program, so trigger warnings when the code below
      # attempts to remove them again. Added if(file.exists) calls below to
      # prevent these warnings.

      for(p in seq_along(programs)){
        if(vcqi_object_exists(paste0(programs[p], "_TEMP_DATASETS"))){
          tempset <- get(paste0(programs[p], "_TEMP_DATASETS"), envir = globalenv())

          if(!is.null(tempset) & length(tempset) > 0){
            for (d in seq_along(tempset)){
              vcqi_log_comment(VCP, 3, "Cleanup",
                               paste0("Erasing temp dataset ", tempset[d]))

              if (stringr::str_detect(tempset[d], ".rds")){
                if(file.exists(paste0(VCQI_OUTPUT_FOLDER, "/", tempset[d]))){
                  file.remove(paste0(VCQI_OUTPUT_FOLDER, "/", tempset[d]))}
              } else {
                if(file.exists(paste0(VCQI_OUTPUT_FOLDER, "/", tempset[d],".rds"))){
                  file.remove(paste0(VCQI_OUTPUT_FOLDER, "/", tempset[d],".rds"))}
              }
            } # end d loop
          }

        }
      } # end p loop
    }

    # ****************************************************************************
    # Let the user know (in console and logfile) if VCQI is exiting prematurely
    if(vcqi_object_value("VCQI_ERROR", 1)){
      message("VCQI is exiting prematurely because of an error.")
      vcqi_log_comment(VCP, 1, "Error", "VCQI is exiting prematurely because of an error.")
    }

    # ****************************************************************************
    # Clean up and close log file

    vcqi_log_comment(VCP, 3, "Comment", "Closing and exporting the log...")

    # vcqi_global(VCQI_LOGOPEN, 0)
    # ^ This overwrites the log - the global is changed and then vcqi_log_global
    # calls vcqi_log_comment which uses the VCQI_LOGOPEN value to determine
    # whether to create a fresh log file.
    assign("VCQI_LOGOPEN", 0, envir = globalenv())

    vhi_log <- read.csv(paste0(VCQI_OUTPUT_FOLDER, "/", VCQI_LOGFILE_NAME, ".csv"))

    # Backup process in case the log file doesn't have appropriate header
    if(any(names(vhi_log) == "level") == FALSE |
       any(names(vhi_log) == "entry_type") == FALSE){
      firstrow <- names(vhi_log)
      firstrow <- ifelse(substr(firstrow, 1, 1) == "X", str_replace(firstrow, "X", ""), firstrow)

      firstrow <- data.frame(
        date = str_replace_all(firstrow[1], fixed("."), "-"),
        time = str_replace_all(firstrow[2], fixed("."), ":"),
        program = firstrow[3],
        level = as.numeric(firstrow[4]),
        entry_type = firstrow[5],
        entry = firstrow[6]
      ) %>%
        mutate(date = as.character(date), time = as.character(time),
               program = as.character(program), level = as.numeric(level),
               entry_type = as.character(entry_type), entry = as.character(entry))

      names(vhi_log) <- c("date", "time", "program", "level", "entry_type", "entry")

      vhi_log <- vhi_log %>%
        mutate(date = as.character(date), time = as.character(time),
               program = as.character(program), level = as.numeric(level),
               entry_type = as.character(entry_type), entry = as.character(entry))

      vhi_log <- bind_rows(firstrow, vhi_log)
    }

    n_logrows <- nrow(vhi_log)
    n_errors <- filter(vhi_log, level %in% 1) %>% nrow()
    n_warnings <- filter(vhi_log, level %in% 2 & entry_type == "Warning") %>% nrow()

    vhi_log <- vhi_log %>%
      mutate(sequence = 1:n()) %>%
      select(sequence, everything()) %>%
      arrange(level, sequence)

    # Rename variables for export to the first row of the log
    names(vhi_log) <- c("Log Sequence", "Date", "Time", "Program", "Level",
                        "Log Entry Type", "Log Entry")

    vhi_wb <- createWorkbook()
    addWorksheet(vhi_wb, "Log")

    errorStyle <- createStyle(bgFill = "#FFC7CE")
    warningStyle <- createStyle(bgFill = "#FFEB9C")
    headerStyle <- createStyle(fgFill = "#D1D1D1")
    centerStyle <- createStyle(halign = "center") ##TO DO double check this gives what we want

    # Format error rows
    conditionalFormatting(
      wb = vhi_wb, sheet = "Log",
      cols = 1:ncol(vhi_log), rows = 2:nrow(vhi_log),
      rule = '$F2="Error"', style = errorStyle
    )

    # Format warning rows
    conditionalFormatting(
      wb = vhi_wb, sheet = "Log",
      cols = 1:ncol(vhi_log), rows = 2:nrow(vhi_log),
      rule = '$F2="Warning"', style = warningStyle
    )

    writeData(vhi_wb, sheet = "Log", vhi_log)

    # Set the widths of the log columns to hold the text
    # expand the column width to hold the text (max allowable width via mata = 255)
    # setColWidths(vhi_wb, sheet = "Log", cols = 1, widths =  12)
    # setColWidths(vhi_wb, sheet = "Log", cols = 2, widths =  12)
    # setColWidths(vhi_wb, sheet = "Log", cols = 3, widths =   9)
    # setColWidths(vhi_wb, sheet = "Log", cols = 4, widths =  30)
    # setColWidths(vhi_wb, sheet = "Log", cols = 5, widths =   6)
    # setColWidths(vhi_wb, sheet = "Log", cols = 6, widths =  15)
    # setColWidths(vhi_wb, sheet = "Log", cols = 7, widths = 225)

    setColWidths(vhi_wb, sheet = "Log",
                 cols = c(1, 2, 3, 4, 5, 6, 7),
                 widths = c(12, 12, 9, 30, 6, 15, 225))

    # Align cell
    addStyle(wb = vhi_wb, sheet = "Log",
      cols = 1, rows = 1:(nrow(vhi_log)+1),
      style = centerStyle)

    addStyle(wb = vhi_wb, sheet = "Log",
      cols = 5, rows = 1:(nrow(vhi_log)+1),
      style = centerStyle)

    # Format headers
    addStyle(wb = vhi_wb, sheet = "Log",
             cols = 1:7, rows = 1,
             style = headerStyle)

    saveWorkbook(
      vhi_wb,
      file = paste0(VCQI_OUTPUT_FOLDER, "/", VCQI_LOGFILE_NAME, ".xlsx"),
      overwrite = TRUE)

    # Replace Log tab in TO file - testing
    to <- openxlsx::loadWorkbook(paste0(VCQI_OUTPUT_FOLDER, "/", VCQI_ANALYSIS_NAME, "_TO.xlsx"))

    # Backup process in case Log tab isn't available
    if(any(names(to) == "Log") == FALSE){
      addWorksheet(to, "Log")
      worksheetOrder(to) <- c(length(names(to)), (1:(length(names(to)) - 1)))
    }

    # Format error rows
    conditionalFormatting(
      wb = to, sheet = "Log",
      cols = 1:ncol(vhi_log), rows = 2:nrow(vhi_log),
      rule = '$F2="Error"', style = errorStyle
    )

    # Format warning rows
    conditionalFormatting(
      wb = to, sheet = "Log",
      cols = 1:ncol(vhi_log), rows = 2:nrow(vhi_log),
      rule = '$F2="Warning"', style = warningStyle
    )

    writeData(to, sheet = "Log", vhi_log)

    setColWidths(to, sheet = "Log",
                 cols = c(1, 2, 3, 4, 5, 6, 7),
                 widths = c(12, 12, 9, 30, 6, 15, 225))

    # Align cell
    addStyle(wb = to, sheet = "Log",
             cols = 1, rows = 1:(nrow(vhi_log)+1),
             style = centerStyle)

    addStyle(wb = to, sheet = "Log",
             cols = 5, rows = 1:(nrow(vhi_log)+1),
             style = centerStyle)

    # Format headers
    addStyle(wb = to, sheet = "Log",
             cols = 1:ncol(vhi_log), rows = 1,
             style = headerStyle)

    saveWorkbook(to, paste0(VCQI_OUTPUT_FOLDER, "/", VCQI_ANALYSIS_NAME, "_TO.xlsx"),
                 overwrite = TRUE)

    # Delete the .csv version of the log
    file.remove(paste0(VCQI_OUTPUT_FOLDER, "/", VCQI_LOGFILE_NAME, ".csv"))

    # Report n-1 if one of the errors is 'VCQI is exiting prematurely' because that's not a separate error
    if (vcqi_object_value("VCQI_ERROR", 1)){
      print(paste0("VCQI ran with ", (n_errors -1), " error messages and ",
                   n_warnings, " warnings."))
    } else {
      print(paste0("VCQI ran with ", n_errors," error messages and ",
                   n_warnings," warnings."))
    }

    if ((n_errors+n_warnings) > 0){
      print(paste0("See the Log worksheet in ", VCQI_OUTPUT_FOLDER, "/",
                   VCQI_LOGFILE_NAME, ".xlsx for more information"))
    }

    # Billboard
    cat(paste(
      r"(====================================================================               )",
      r"(                 VACCINATION COVERAGE QUALITY INDICATORS                           )",
      r"(  ====================================================================             )",
      r"(   __/\\\________/\\\________/\\\\\\\\\________/\\\________/\\\\\\\\\\\_           )",
      r"(    _\/\\\_______\/\\\_____/\\\////////______/\\\\/\\\\____\/////\\\///__          )",
      r"(     _\//\\\______/\\\____/\\\/_____________/\\\//\////\\\______\/\\\_____         )",
      r"(      __\//\\\____/\\\____/\\\______________/\\\______\//\\\_____\/\\\_____        )",
      r"(       ___\//\\\__/\\\____\/\\\_____________\//\\\______/\\\______\/\\\_____       )",
      r"(        ____\//\\\/\\\_____\//\\\_____________\///\\\\/\\\\/_______\/\\\_____      )",
      r"(         _____\//\\\\\_______\///\\\_____________\////\\\//_________\/\\\_____     )",
      r"(          ______\//\\\__________\////\\\\\\\\\_______\///\\\\\\___/\\\\\\\\\\\_    )",
      r"(           _______\///______________\/////////__________\//////___\///////////__   )",
      r"(            =====================================================================  )",
      r"(                                (C) WORLD HEALTH ORGANIZATION                      )",
      r"(                             (C) PAN AMERICAN HEALTH ORGANIZATION                  )",
      r"(              =====================================================================)",
      r"()",
      sep = "\n"
    ))

    # ****************************************************************************
    # Exit with error code, if appropriate

    if (vcqi_object_value("VCQI_ERROR", 1)){
      cleanup_VCQI_globals()

      if(all(is.na(halt_message))){halt_message <- ""} # message must be a character vector

      rlang::abort(message = halt_message,
                   call = NULL)
    } else {
      cleanup_VCQI_globals()
    }

    # Establish a global for the control program to use that
    # is the same as the 'quietly{' command.  This will suppress
    # writing the change log to the screen and instead leave a
    # last line in the log window that says:
    # VCQI____END_OF_PROGRAM

    # global VCQI____END_OF_PROGRAM  set output error

  } # end VCQI_CHECK_INSTEAD_OF_RUN if()

}
